### ISSUE TITLE
Automate the Integration test with Github Actions and run Daily

### ISSUE THREAD

**Issue by clun** [datastax/astra-sdk-java#24]

**Comment by kidrecursive** [comment]
I had this work locally, pushed it up to a branch here: https://github.com/datastax/astra-sdk-java/tree/tests

The only thing to do would be to add the necessary secrets (under settings) and everything "should" work.

**Comment by kidrecursive** [comment]
https://github.com/datastax/astra-sdk-java/pull/26/checks?check_run_id=3700530794
