### ISSUE TITLE
bash 'complete' command not found on recent zsh macs

### ISSUE THREAD

**Issue by stinkymatt** [datastax/astra-sdk-java#45]
After the curl install, creating a new Terminal prints out: "/Users/<user>/.astra/cli/astra-init.sh:1155: command not found: complete"

**Comment by clun** [comment]
The CLI now has a dedicated repository.
I copied the issue there https://github.com/datastax/astra-cli/issues/1 and will close ths one.

Solution we are working on adding in the script 
```
autoload -U +X bashcompinit && bashcompinit
autoload -U +X compinit && compinit
```
