### ISSUE TITLE
Change default connection.pool.local.size

### ISSUE THREAD

**Issue by bhisey** [datastax/astra-sdk-java#58]
Hi Team,
Astra is using DSE which is based on TPC, a lower value of the local connection pool will cause more issues that benefit, can we bump this value to a higher say 8, and add it clearly in documentation to configure it correctly?
```
    { "name": "astra.cql.driver-config.advanced.connection.pool.local.size",
      "type": "java.lang.Integer",
      "description":"The number of connections in the pool.",
      "defaultValue": "1" },
```

**Comment by ErickRamirezAU** [comment]
The default `pool.local.size = 1` works in almost all cases. Can you provide a bit more context, like what problem are you trying to solve? It help us understand if we have a bit more background. Cheers!

**Comment by clun** [comment]
Any update @bhisey  ? Thank you

**Comment by clun** [comment]
After tests with internal team 1 is the recommended value, you can still update it in your own `application.conf`
